name: CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t your-docker-username/ci-cd-example:latest .

    - name: List Docker images
      run: docker images

    - name: Push Docker image to Docker Hub
      run: |
        docker push your-docker-username/ci-cd-example:latest
